[platformio]
default_envs = dfr1221

[env:dfr1221]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = esp_sr_16.csv
board_upload.flash_size = 16MB
extra_scripts = pre:scripts/add_sr_model.py
build_flags =
  -I include
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_USE_MALLOC
  -D LV_CONF_INCLUDE_SIMPLE
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  lvgl/lvgl@8.3.11
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v0.1.4
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v0.0.2
