[platformio]
default_envs = dfr1221

[env:dfr1221]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D BOARD_HAS_PSRAM
  -D CONFIG_SPIRAM_USE_MALLOC
  -D LV_CONF_SKIP
  -D LV_COLOR_16_SWAP=1
  -D LV_FONT_MONTSERRAT_12=1
  -D LV_FONT_MONTSERRAT_16=1
  -D LV_FONT_MONTSERRAT_20=1
  -D LV_FONT_SIMSUN_16_CJK=1
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  lvgl/lvgl@8.4.0
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v0.1.4
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v0.0.2
